### ISSUE TITLE
Peer Dependencies problem with React v17.0.1

### ISSUE THREAD

**Issue by MrNossiom** [sag1v/react-elastic-carousel#140]
**Describe the bug**
You got a peer dependencies error with react when using v17.0.1

**To Reproduce**
1. Create a React project using CRA anything like that...
2. Install react-elastic-carousel using npm
3. See peer dependencies error

**To Fix**
Upgrade peer dependencies to React and React-DOM v17.0.1

|Software|Version|
|-|-|
|OS|Win10 with WSL2|
|NodeJS|v15.5.0|
|NPM|v7.3.0|
|React|v17.0.1|
|react-elastic-gallery|v0.10.0|

**Comment by sag1v** [comment]
@MrNossiom Thanks. fixed as of version `0.11.0`

**Comment by MrNossiom** [comment]
Thanks

**Comment by aarowman** [comment]
@sag1v This is covered here, but is still an issue on `react-only-when`, which is a peer dependency here.

See https://github.com/sag1v/react-only-when/issues/2

**Comment by aarowman** [comment]
Note: when could consider using `>=15.0.0` instead, and then we won't run into issues for each React version

**Comment by gian-luca-weston** [comment]
Still believe this is an issue as react-only-when@1.0.2 (which seems to be the only version) depends on react@^16.4.1 meaning this can't be used in react 17

**Comment by DruxAMB** [comment]
React Elastic Carousel can't work in the latest version of Reactjs
