### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by daniteohotmail** [sag1v/react-elastic-carousel#172]
When I fast change the page on my website, sometimes I get this error on browser console:

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. Carousel@http://localhost:3000/static/js/vendors~main.chunk.js:56014:20 
div 
Container@http://localhost:3000/static/js/vendors~main.chunk.js:79174:18 
.....

The part of code reported by console is this:

```
function Carousel(props) {
    var _this;

    _classCallCheck(this, Carousel);
```

I know it's not a big deal but it's a bit annoying. 
Or I wrong something in the implementation?

Thank you for your job.

**Comment by sag1v** [comment]
Thanks @daniteohotmail .
Are you using `enableAutoPlay` prop?

I couldn't reproduce it but i think i know why it's happening. I released a beta version with a fix, can you please try installing version `0.11.5-beta.1` and let me know if the problem is fixed?

**Comment by daniteohotmail** [comment]
Hi, enableAutoPlay is false. 
I install the 0.11.5-beta.1 version but the problem is still happening.
Can I do any other tests to help you?

**Comment by sag1v** [comment]
Hmm interesting. Well, a reproducible example can help a lot.

**Comment by danielefontana95** [comment]
Hi (I'm the same person with my new account).
I create this sandbox for reproduce it.
https://codesandbox.io/s/crimson-pine-ycu2u
Click two times the button and in console will appear the error.

**Comment by sag1v** [comment]
@danielefontana95 Thanks! please try this version and let me know `0.11.5-beta.2`

**Comment by danielefontana95** [comment]
@sag1v Hi! I tested with the  `0.11.5-beta.2` version but the error still happening...

**Comment by sag1v** [comment]
@danielefontana95 Sorry, i published a wrong beta version. Can you try `0.11.5-beta.3` please?

**Comment by danielefontana95** [comment]
Yesssss! It seems to be working correctly now.
Thank you, very great job!

**Comment by sag1v** [comment]
@danielefontana95 Great. I published it with official release under version `0.11.5`
