### ISSUE TITLE
Using both renderPagination and breakPoints on <Carousel /> breaks the pages property in renderPagination

### ISSUE THREAD

**Issue by mathiasjakobsen** [sag1v/react-elastic-carousel#71]
**Describe the bug**
When combining the `renderPagination` and `breakPoints` props on `<Carousel />` the `pages` in `({ pages, activePage, onClick }) =>` does not take the current breakpoints `itemsToShow` into consideration.

**To Reproduce**
Given a `<Carousel />` with 9 items, at a breakpoint showing 3 items per page will have `pages` be `[1, 2, 3, 4, 5, 6, 7, 8, 9]` rather than the expected `[1, 2, 3]`, when using the `breakPoints` props rather than the `itemsToShow` prop directly on `<Carousel />`.

**Expected behavior**
The expected content of `pages` is `[1, 2, 3]`

**Screenshots**
No screenshots. 

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Chrome
 - Version: 84.0.4147.125 (Official Build) (64-bit)

**Comment by sag1v** [comment]
Thanks @mathiasjakobsen! 🙏 
This is a regression due to a fix of #58. 
Fixed as of version `0.7.3`

**Comment by mathiasjakobsen** [comment]
@sag1v thank for the ultra quick response time. However, the problem still occurs when using latest release. I think it's due to the difference between the default pagination and a passed `renderPagination` function, in https://github.com/sag1v/react-elastic-carousel/blob/master/src/react-elastic-carousel/components/Carousel.js#L575-L586. `numOfPages` takes `itemsToShow` into consideration, since 9 slides will fit on 3 pages if the `itemsToShow` is 3. However, `pages` seems to include 9 pages even if `itemsToShow` is 3.
